#smtp mail properties
mail:
  smtp:
    auth: true
    starttlsEnable: true
    host: smtp.gmail.com
    port: 587
    username: test12@gmail.com
    password: test@12
    protocol: smtp
    senderName: Test Test
    senderEmail: test@gmail.com